version: "3"
services:

  # Demo MAB flask App
  app:
    build: .
    restart: always
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=app.py
      - ENV=prod
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - AB_HOST=redis
      - AB_PORT=6379
      - AB_DB=0
    links:
      - redis
    volumes:
      - ./app:/app

  # NGINX in front of our flask app  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
    ports:
      - 5000:5000
      # - 80:80
      # - 443:443

  # Redis stores trials/successes
  redis:
    image: redis
    volumes:
      - ./data:/data
